"use client"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { BarChart3, Eye, MousePointerClick, RefreshCw, ShoppingBag, Users } from "lucide-react"
import AdminHeader from "../components/AdminHeader"
import { adminLogout, fetchAnalytics, getAdminToken, type AnalyticsSummary } from "../../lib/api"
function pct(a:number,b:number){return b?`${Math.min(100,(a/b)*100).toFixed(1)}%`:'0%'}
export default function AnalyticsPage(){
 const router=useRouter();const[days,setDays]=useState(30);const[data,setData]=useState<AnalyticsSummary|null>(null);const[loading,setLoading]=useState(true)
 async function load(){setLoading(true);try{setData(await fetchAnalytics(days))}finally{setLoading(false)}}
 useEffect(()=>{if(!getAdminToken()){router.push('/admin/login');return}load()},[days])
 const c=data?.counts||{page_view:0,product_view:0,add_to_cart:0,begin_checkout:0,purchase:0}
 const stages=[c.page_view,c.product_view,c.add_to_cart,c.begin_checkout,c.purchase]
 return <main dir="rtl" className="min-h-screen bg-[var(--bg)]"><AdminHeader onLogout={()=>{adminLogout();router.push('/admin/login')}}/><section className="mx-auto max-w-7xl px-5 py-8"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs tracking-[.2em] text-gray-400">DAHAB ANALYTICS</p><h1 className="mt-1 text-3xl font-semibold">تحليل سلوك العملاء</h1><p className="mt-2 text-sm text-gray-500">من دخول الموقع لحد إتمام الطلب.</p></div><div className="flex gap-2">{[7,30,90].map(x=><button key={x} onClick={()=>setDays(x)} className={`rounded-xl border px-4 py-2 text-sm ${days===x?'border-black bg-black text-white':'border-black/10 bg-white'}`}>{x} يوم</button>)}<button onClick={load} className="rounded-xl border border-black/10 bg-white px-3"><RefreshCw size={16}/></button></div></div>{loading?<div className="rounded-2xl bg-white p-10 text-center text-gray-500">جارِ تحميل التحليلات...</div>:<><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[[Users,'جلسات',data?.uniqueSessions||0],[Eye,'مشاهدات',c.page_view],[BarChart3,'مشاهدات المنتجات',c.product_view],[MousePointerClick,'إضافات للسلة',c.add_to_cart],[ShoppingBag,'طلبات',c.purchase]].map(([I,l,v])=>{const Icon=I as typeof Users;return <div key={String(l)} className="rounded-2xl border border-black/10 bg-white p-5"><Icon size={19} className="text-gray-400"/><p className="mt-4 text-sm text-gray-500">{l as string}</p><p className="mt-1 text-2xl font-semibold">{Number(v).toLocaleString('ar-EG')}</p></div>})}</div><section className="mt-5 rounded-2xl border border-black/10 bg-white p-5"><h2 className="font-semibold">رحلة الشراء</h2><div className="mt-6 grid gap-3 md:grid-cols-5">{[[c.page_view,'زيارة'],[c.product_view,'مشاهدة منتج'],[c.add_to_cart,'إضافة للسلة'],[c.begin_checkout,'بدء الدفع'],[c.purchase,'إتمام الطلب']].map(([v,l],i)=><div key={String(l)} className="rounded-2xl bg-neutral-50 p-4"><p className="text-xs text-gray-400">{l as string}</p><p className="mt-2 text-xl font-semibold">{Number(v).toLocaleString('ar-EG')}</p>{i>0&&<p className="mt-2 text-xs text-[var(--brand-dark)]">{pct(Number(v),Number(stages[i-1]))} من المرحلة السابقة</p>}</div>)}</div></section><section className="mt-5 rounded-2xl border border-black/10 bg-white p-5"><h2 className="mb-5 font-semibold">أكثر المنتجات مشاهدة</h2><div className="space-y-3">{data?.topProducts.length?data.topProducts.map((p,i)=><div key={p.product_id} className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-neutral-100 text-sm font-semibold">{i+1}</span><span className="min-w-0 flex-1 truncate text-sm">{p.name}</span><span className="text-sm text-gray-500">{p.views.toLocaleString('ar-EG')} مشاهدة</span></div>):<p className="text-sm text-gray-400">لسه مفيش بيانات كفاية.</p>}</div></section></>}</section></main>
}
