"use client"
import { useEffect, useMemo, useState } from "react"
import { Bell, Package, AlertTriangle, MessageCircle, RefreshCw, ArrowLeft } from "lucide-react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { getAdminToken, adminLogout, fetchAdminOrders, fetchAdminProducts, fetchContactMessages } from "../../lib/api"
import AdminHeader from "../components/AdminHeader"
export default function NotificationsPage(){
 const router=useRouter();const[orders,setOrders]=useState<any[]>([]);const[products,setProducts]=useState<any[]>([]);const[messages,setMessages]=useState<any[]>([]);const[loading,setLoading]=useState(true)
 async function load(){setLoading(true);try{const[a,b,c]=await Promise.all([fetchAdminOrders(),fetchAdminProducts(),fetchContactMessages()]);setOrders(a);setProducts(b);setMessages(c)}finally{setLoading(false)}}
 useEffect(()=>{if(!getAdminToken()){router.push('/admin/login');return}load()},[])
 const items=useMemo(()=>{const now=Date.now();const out:any[]=[];orders.filter(o=>o.status==='جديد').slice(0,10).forEach(o=>out.push({key:'o'+o.id,type:'order',title:`طلب جديد #DAH-${o.id}`,body:`${o.customer_name} — ${Number(o.total||0).toLocaleString('ar-EG')} ج.م`,time:new Date(o.created_at).getTime(),href:'/admin/orders'}));products.filter(p=>Number(p.stock||0)===0||Number(p.stock||0)<=Number(p.lowStockThreshold||5)).slice(0,10).forEach(p=>out.push({key:'p'+p.id,type:'stock',title:Number(p.stock||0)===0?`نفد المخزون: ${p.name}`:`مخزون منخفض: ${p.name}`,body:`المتاح ${Number(p.stock||0).toLocaleString('ar-EG')} قطعة`,time:now,href:'/admin/inventory'}));messages.filter(m=>!m.is_read).slice(0,10).forEach(m=>out.push({key:'m'+m.id,type:'message',title:`رسالة جديدة من ${m.name}`,body:m.message,time:new Date(m.created_at).getTime(),href:'/admin/messages'}));return out.sort((a,b)=>b.time-a.time)},[orders,products,messages])
 return <main dir="rtl" className="min-h-screen bg-[var(--bg)]"><AdminHeader unreadCount={messages.filter(m=>!m.is_read).length} onLogout={()=>{adminLogout();router.push('/admin/login')}}/><section className="mx-auto max-w-5xl px-5 py-8"><div className="mb-6 flex items-end justify-between"><div><p className="text-xs text-gray-400">مركز المتابعة</p><h1 className="mt-1 text-3xl font-semibold">الإشعارات</h1><p className="mt-2 text-sm text-gray-500">طلبات جديدة، مخزون منخفض، ورسائل العملاء.</p></div><button onClick={load} className="flex items-center gap-2 rounded-xl border border-black/10 bg-white px-4 py-2.5 text-sm"><RefreshCw size={15}/> تحديث</button></div>{loading?<div className="rounded-2xl bg-white p-10 text-center text-gray-500">جارِ التحميل...</div>:items.length===0?<div className="rounded-2xl bg-white p-12 text-center"><Bell className="mx-auto text-gray-300" size={40}/><p className="mt-4 font-medium">مفيش إشعارات جديدة 🎉</p></div>:<div className="space-y-3">{items.map(x=><Link href={x.href} key={x.key} className="flex items-center gap-4 rounded-2xl bg-white p-4 shadow-sm transition hover:shadow"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-neutral-100">{x.type==='order'?<Package size={19}/>:x.type==='stock'?<AlertTriangle size={19}/>:<MessageCircle size={19}/>}</div><div className="min-w-0 flex-1"><p className="font-medium">{x.title}</p><p className="mt-1 truncate text-sm text-gray-500">{x.body}</p></div><ArrowLeft size={17} className="text-gray-400"/></Link>)}</div>}</section></main>
}
