"use client"
import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import { Check, EyeOff, RefreshCw, Star, Trash2 } from "lucide-react"
import AdminHeader from "../components/AdminHeader"
import { adminLogout, deleteReview, fetchAdminReviews, getAdminToken, updateReviewStatus, type ProductReview } from "../../lib/api"
type ReviewRow = ProductReview & { product_name?: string }
export default function ReviewsPage(){
 const router=useRouter(); const [reviews,setReviews]=useState<ReviewRow[]>([]); const [loading,setLoading]=useState(true)
 async function load(){setLoading(true);try{setReviews(await fetchAdminReviews() as ReviewRow[])}finally{setLoading(false)}}
 useEffect(()=>{if(!getAdminToken()){router.push('/admin/login');return}load()},[])
 async function status(id:number,status:"approved"|"hidden"|"pending"){await updateReviewStatus(id,status);setReviews(r=>r.map(x=>x.id===id?{...x,status}:x))}
 async function remove(id:number){if(!confirm('حذف التقييم نهائيًا؟'))return;await deleteReview(id);setReviews(r=>r.filter(x=>x.id!==id))}
 return <main dir="rtl" className="min-h-screen bg-[var(--bg)]"><AdminHeader onLogout={()=>{adminLogout();router.push('/admin/login')}}/><section className="mx-auto max-w-6xl px-5 py-8"><div className="mb-6 flex items-end justify-between"><div><p className="text-xs tracking-[.2em] text-gray-400">CUSTOMER REVIEWS</p><h1 className="mt-1 text-3xl font-semibold">تقييمات العملاء</h1><p className="mt-2 text-sm text-gray-500">راجعي التقييمات قبل ظهورها على صفحات المنتجات.</p></div><button onClick={load} className="flex items-center gap-2 rounded-xl border border-black/10 bg-white px-4 py-2.5 text-sm"><RefreshCw size={15}/> تحديث</button></div>{loading?<div className="rounded-2xl bg-white p-10 text-center text-gray-500">جارِ التحميل...</div>:reviews.length===0?<div className="rounded-2xl bg-white p-12 text-center text-gray-400">لا توجد تقييمات حتى الآن.</div>:<div className="space-y-3">{reviews.map(r=><article key={r.id} className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-3"><h2 className="font-medium">{r.customer_name}</h2><div className="flex text-[var(--brand)]">{[1,2,3,4,5].map(i=><Star key={i} size={14} className={i<=r.rating?'fill-current':''}/>)}</div><span className="rounded-full bg-neutral-100 px-2 py-1 text-[10px]">{r.status==='approved'?'معتمد':r.status==='hidden'?'مخفي':'قيد المراجعة'}</span></div><p className="mt-2 text-xs text-gray-400">{r.product_name||`منتج #${r.product_id}`} · {new Date(r.created_at).toLocaleDateString('ar-EG')}</p><p className="mt-4 text-sm leading-7 text-gray-600">{r.comment}</p></div><div className="flex shrink-0 gap-2"><button onClick={()=>status(r.id,'approved')} className="flex items-center gap-1 rounded-xl border border-emerald-100 px-3 py-2 text-xs text-emerald-700"><Check size={14}/> اعتماد</button><button onClick={()=>status(r.id,'hidden')} className="flex items-center gap-1 rounded-xl border border-amber-100 px-3 py-2 text-xs text-amber-700"><EyeOff size={14}/> إخفاء</button><button onClick={()=>remove(r.id)} className="rounded-xl border border-red-100 px-3 py-2 text-red-600"><Trash2 size={14}/></button></div></div></article>)}</div>}</section></main>
}
